### ISSUE TITLE
webapp 1.2 now conflicts with Symfony <6.2?

### ISSUE THREAD

**Issue by ahundiak** [symfony/webapp-pack#10]
The problem is that the Symfony 5 LTS appears to use webapp 1.2 resulting in composer version issues.
```
symfony new --webapp --version=lts s54webapp
- symfony/webapp-pack v1.2.0 conflicts with symfony/framework-bundle <6.2.
```
Manually changing the webapp version to 6.1 fixes the issue.  But something needs to be tweaked.

**Comment by nicolas-grekas** [comment]
I removed the tag and reverted the conflict in https://github.com/symfony/webapp-pack/commit/124fb85d004a1ab32de7af86f0d73b9e8fd1136f
